// const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
// const COINGECKO_API_URL = process.env.REACT_APP_COINGECKO_API;
// const EXCHANGE_API_URL = process.env.REACT_APP_EXCHANGE_API;

// export { API_BASE_URL, COINGECKO_API_URL, EXCHANGE_API_URL };


const API_BASE_URL = process.env.REACT_APP_API_BASE_URL.endsWith("/")
  ? process.env.REACT_APP_API_BASE_URL
  : process.env.REACT_APP_API_BASE_URL + "/";

const COINGECKO_API_URL = process.env.REACT_APP_COINGECKO_API;
const EXCHANGE_API_URL = process.env.REACT_APP_EXCHANGE_API;

export { API_BASE_URL, COINGECKO_API_URL, EXCHANGE_API_URL };
